### ISSUE TITLE
Issue: particles picked by Topaz are not displayed in Relion GUI

### ISSUE THREAD

**Issue by UHeinemeyer** [tbepler/topaz#102]
I try to get started with Topaz particle picking by running it in the Relion GUI via the external job. 
Although I do pick particles as it is shown in the topaz_picks.txt file the coords_suffic_topazpicks.star file, relevant for visualizing the picks in the Relion GUI is always empty, Independent of the choice of parameters (e.g. selectionthreshold). There are no errors visible. What is the issue?

Warning: Failed writing log files to directory [/var/log/nvidia-mps]. No logs will be available.
# OUTPUT format: coord
This wrapper runs TOPAZ
Please provide a micrograph.star as input and a model for picking.
If your TOPAZ installation is not /software/app/smlc.nysbc.org/topaz/0.2.5b/rt_intel_impi/2020.2/bin/topaz, then add the parameter: topaz_path
Additionally, these parameters may be changed: scalefactor, radius, trained_model, pick_threshold, select_threshold, 
If other parameters might be useful and should be included please let us know.
If you want to re-run the job to just select particles with a different threshold, set the parameter --skip_pick to True and continue the job.
running ...
Preprocessing...
Running command: /software/app/smlc.nysbc.org/topaz/0.2.5b/rt_intel_impi/2020.2/bin/topaz preprocess `relion_star_printtable CtfFind/job016/micrographs_ctf.star data_micrographs _rlnMicrographName` --scale 5  --sample 1 --num-workers -1 --format mrc --device 0 --niters 100 --alpha 900 --beta 1 --verbose --destdir External/job033/PreProcessed
Making star files...
Running command: /software/app/smlc.nysbc.org/topaz/0.2.5b/rt_intel_impi/2020.2/bin/topaz extract External/job033/PreProcessed/*mrc --model resnet8_u64 --radius 15 --threshold -2.0 --up-scale 1 --batch-size 1 --min-radius 5 --max-radius 100 --step-radius 5 --num-workers -1 --device 0 --output External/job033/topaz_picks.txt
Selecting particles...
Running command: /software/app/smlc.nysbc.org/topaz/0.2.5b/rt_intel_impi/2020.2/bin/topaz convert External/job033/topaz_picks.txt --threshold 0 --up-scale 5 --down-scale 1 --voltage -1 --detector-pixel-size -1 --magnification -1 --amplitude-contrast -1 --boxsize 0 --image-ext .mrc --verbose 1 --output  External/job033/topaz_picks_scaled.txt
Making star files...
star files done
All done!
 
Thanks for your support,
Ute

**Comment by tbepler** [comment]
Are you able to run topaz from the command line?

**Comment by UHeinemeyer** [comment]
Yes, I can run topaz from the command line. The preprocessed data and particle picks are also displayed in the GUI.

**Comment by tbepler** [comment]
Ok, sounds like an issue with RELION integration then and not your topaz install. @alexjnoble @rfleiro have you guys ever run into any issues like this with the RELION scripts or have any idea what could be going on?

**Comment by UHeinemeyer** [comment]
It´s the same issue that zruan reported in February. Excuse me for not recognizing it. The coords_suffix_topazpicks.star was always fine (the coordinates are not stored there).
