### ISSUE TITLE
Can't open the walkthrough

### ISSUE THREAD

**Issue by rudaluna** [tbepler/topaz#11]
Hi,

I can't open the walkthrough on GitHub, it's giving me this error:

Sorry, something went wrong. Reload?

And it never loads. I'm reading it as a text file but it's a little annoying. Am I missing something? Does it need Jupyter installed?

Best regards,

------------------------------------------------
Ruda Santos, PhD student
Huilin Li Lab, Van Andel Institute

**Comment by alexjnoble** [comment]
Hi Ruda,

I have found that the walkthrough works in some browsers and not others. For me, it works on Firefox 66 and Google Chrome 73 without anything extra installed.

Let us know if that works.

Best,
-Alex

**Comment by rudaluna** [comment]
Hey Alex,

It did! I was using Safari and changed to Firefox.

Thanks!
