### ISSUE TITLE
0.2.5 vs 0.2.5a

### ISSUE THREAD

**Issue by jjv5** [tbepler/topaz#169]
Conda lists as available and will install version 0.2.5a. The source code only contains version string 0.2.5. 

Is version 0.2.5a from conda different?

`
topaz                          0.0.0            py_2  tbepler             
topaz                          0.1.0            py_0  tbepler             
topaz                          0.2.0            py_0  tbepler             
topaz                          0.2.1            py_0  tbepler             
topaz                          0.2.2            py_0  tbepler             
topaz                          0.2.3            py_0  tbepler             
topaz                          0.2.4            py_0  tbepler             
topaz                         0.2.5a            py_0  tbepler             
topaz                          0.2.5            py_0  tbepler 

`

**Comment by DarnellGranberry** [comment]
Version 0.2.5 (tagged for release) includes a few things like test scaffolding and GitHub automation updates that 0.2.5a doesn't. Please use 0.2.5 to be most up-to-date.
