### ISSUE TITLE
Running topaz denoise

### ISSUE THREAD

**Issue by ojasvijain** [tbepler/topaz#181]
Hi I wanted some help in running topaz denoise. I am trying to follow the [jupyter notebook](https://github.com/tbepler/topaz/blob/master/tutorial/04_denoising.ipynb) for using the topaz denoising algorithm and want to use the pretrained model for some micrographs.

I created a conda environment called "topaz_denoising" and have cloned the repository in another folder called topaz/
now my directory structure looks like:

envs/topaz_denoising
topaz/topaz/./
data/micrographs/*.mrc (files)

can you help me with what commands i should run? currently the one in the jupyter notebook 
`topaz denoise --patch-size 1024 -o data/EMPIAR-10025/denoised/ data/EMPIAR-10025/rawdata/micrographs/*.mrc` 
is not working for me since it cant recognise topaz and denoise as commands.

Thanks!

**Comment by ojasvijain** [comment]
Thank you for your response!

I followed the installation steps you mentioned. I'm getting the following error when i run 
`topaz --version`

![image](https://github.com/tbepler/topaz/assets/41644996/3192cf16-2e13-4ee9-8bd0-8f06db4dc289)

**Comment by Guillawme** [comment]
I have no idea what causes this error, sorry. All I can think of it to try again in an empty conda environment, in case this wasn't already what you did.
Last time I used this installation method it worked without any problem, on two different computers.

**Comment by ojasvijain** [comment]
Thank you for your response

Surprisingly, it worked when I ran it again today morning, not sure why it gave that error yesterday!

I am now facing this issue while using the pretrained denoising unet model on running this command:
`topaz denoise /vast/projects/miti2324/data/cryoppp_data/cryoppp/10017/micrographs/*.mrc -o /vast/projects/miti2324/trial_algorithms/topaz_denoising/output_imgs/ -m ./pretrained/denoise/unet_L2_v0.2.1.sav --patch-size 1024`

The error is:
![image](https://github.com/tbepler/topaz/assets/41644996/898539e2-06e0-4982-9dc9-ff130e3a8d77)

Looks like an error in loading the model in the script. What do you recommend I do?

**Comment by Guillawme** [comment]
The error seems pretty clear: `Found no NVIDIA driver on your system.`
Whether this is accurate or not I don't know, so first check that the command `nvidia-smi` returns a table with a list of GPUs. If it does, then there's a problem with your topaz installation not seeing the GPU. If it doesn't, then you need to try on a system with an nvidia GPU and the nvidia driver installed.

**Comment by ojasvijain** [comment]
I have nvidia installed but the error still persists. I guess it just throws a warning for the GPU but should still work on the CPU. 

However, the error per se seems to be while loading the model, especially in the model.eval() code block in main. Is this due to a version conflict? Here is my package list
![image](https://github.com/tbepler/topaz/assets/41644996/cff1db04-c666-4670-af8c-5a8ce33f8e1a)

**Comment by ojasvijain** [comment]
It seems like the model path i was providing was incorrect so i just deleted with argument for it.

Its working perfectly now! Thanks
