### ISSUE TITLE
Bug with Topaz

### ISSUE THREAD

**Issue by win5tan** [tbepler/topaz#207]
Hi there, it looks like there's a bug with Topaz. The line where it is erroring is bad. 

It should be:

pd.concat(groups_train, axis=0)

Instead of 

pd.concat(groups_train, 0) <--- BAD!

Could the developers please debug/fix it? Thanks a lot.

**Comment by DarnellGranberry** [comment]
What file and line is it referencing in your error?

**Comment by win5tan** [comment]
Hi Darnell,

It was when I execute the Topaz path in cryosparc. IT officer from my
institute thinks it's a bug error.

I used the following Topaz path:
/stornext/System/data/software/rhel/9/base/structbio/topaz/0.2.5/bin/topaz

Thanks,
Winnie

**Comment by DarnellGranberry** [comment]
The only instances of pd.concat I can find all use that keyword argument. Can you try re-installing topaz? It would be helpful if you could paste the full traceback output when your error appears.

**Comment by DarnellGranberry** [comment]
Please update your installations and let us know if there are further issues

**Comment by DarnellGranberry** [comment]
Please update your installations and let us know if there are further issues

**Comment by DarnellGranberry** [comment]
Hi @win5tan . If you are still having issues, that should be fixed in v0.3.5.
