### ISSUE TITLE
Compatibility with H100 GPUs

### ISSUE THREAD

**Issue by taceysa** [tbepler/topaz#208]
Hello, we recently installed Topaz using the steps outlined in the Installation instructions. However, we noticed that Python v3.6 seems to be incompatible with more recent versions of PyTorch. The version of PyTorch that is compatible with Python v3.6, however, is incompatible with the newer NVIDIA GPUs (L4, L40, H100). Thus, we are limited in which GPUs we can run Topaz workflows on. 

Is there any plan to update the packages so that they can be compatible with more recent GPU releases? Or is there a workaround to use more recent package versions?

**Comment by DarnellGranberry** [comment]
Topaz has worked with newer python version (3.7-3.9 at least). It would be safest to create a new conda environment specifying that newer python version, and then install topaz.
