### ISSUE TITLE
Version reporting

### ISSUE THREAD

**Issue by epkumpu** [tbepler/topaz#210]
Hi,

Very minor issue here, but I want to make sure this is not something I am doing a bad job at. I recently containerized topaz 0.3.0 and when running topaz --version the output is 0.2.5 even though I explicitly installed 0.3.0. I opened my container and verified that indeed 0.3.0 is installed within. And now that I checked, it seems that __version__ is still 0.2.5 in the current codebase here.

Cheers,
Esa-Pekka

**Comment by DarnellGranberry** [comment]
I've updated \_version.py to 0.3.0. Thanks!
