### ISSUE TITLE
Training test dataset failed

### ISSUE THREAD

**Issue by mplockhartuom** [tbepler/topaz#26]
Hi

I just installed topaz and tried to run it on the test data but ran into problems with training the model. Any help would be greatly appreciated.

## Envs
`conda create -n topaz python=3.7`

## Install
`conda install topaz -c tbepler -c pytorch`

I also tried installing using `conda install topaz cudatoolkit=9.1 -c tbepler -c pytorch` was given package not found errors for `cudatoolkit=9.1` so tried 9.0

## Command

`topaz train --train-images /home/mqbpkml3/em/topaz/data/EMPIAR-10025/preprocessed/micros --train-targets /home/mqbpkml3/em/topaz/data/EMPIAR-10025/topaz_picks_3Jun2019_19h59m.csv --k-fold 5 --fold 0 --radius 7 --model resnet8 --image-ext .png --units 32 --dropout 0.0 --bn on --unit-scaling 2 --ngf 32 --method GE-binomial --autoencoder 0 --num-particles 300 --l2 0 --learning-rate 0.0002 --minibatch-size 256 --minibatch-balance 0.0625 --epoch-size 5000 --num-epochs 10 --num-workers -1 --test-batch-size 1 --device 1 --save-prefix /home/mqbpkml3/em/topaz/data/EMPIAR-10025/topaz_output/training/model --output /home/mqbpkml3/em/topaz/data/EMPIAR-10025/topaz_output/training/results.txt`

## Result

`# Loading model: resnet8`
`# Model parameters: units=32, dropout=0.0, bn=on`
`# Receptive field: 71`
`# Using device=1 with cuda=True`
`# Loaded 30 training micrographs with 80 labeled particles`
`# Split into 24 train and 6 test micrographs`
`# source        split   p_observed      num_positive_regions    total_regions`
`# 0     train   0.00181 9638    5322240`
`# 0     test    0.00168 2235    1330560`
`# Specified expected number of particle per micrograph = 300.0`
`# With radius = 7`
`# Setting pi = 0.20156926406926406`
`# minibatch_size=256, epoch_size=5000, num_epochs=10`
`Traceback (most recent call last):`
`  File "/home/mqbpkml3/anaconda3/envs/topaz/bin/topaz", line 11, in <module>
    load_entry_point('topaz==0.2.0', 'console_scripts', 'topaz')()`
`  File "/home/mqbpkml3/anaconda3/envs/topaz/lib/python3.7/site-packages/topaz/main.py", line 146, in main`
`    args.func(args)`
`  File "/home/mqbpkml3/anaconda3/envs/topaz/lib/python3.7/site-packages/topaz/commands/train.py", line 655, in main`
`    , save_prefix=save_prefix, use_cuda=use_cuda, output=output)`
`  File "/home/mqbpkml3/anaconda3/envs/topaz/lib/python3.7/site-packages/topaz/commands/train.py", line 548, in fit_epochs`
`    , use_cuda=use_cuda, output=output)`
`  File "/home/mqbpkml3/anaconda3/envs/topaz/lib/python3.7/site-packages/topaz/commands/train.py", line 528, in fit_epoch`
`    metrics = step_method.step(X, Y)`
`  File "/home/mqbpkml3/anaconda3/envs/topaz/lib/python3.7/site-packages/topaz/methods.py", line 123, in step`
`    log_binom = scipy.stats.binom.logpmf(np.arange(0,N+1),N,self.pi)`
`  File "/home/mqbpkml3/anaconda3/envs/topaz/lib/python3.7/site-packages/torch/tensor.py", line 458, in __array__`
`    return self.numpy()`
`TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

**Comment by tbepler** [comment]
Thank you for bringing this to my attention! This was a quite an oversight in the 0.2.0 version release from last week. I just pushed out a fix which you can get by reinstalling from conda.

Fixed in commit e455d11bd192aa9f7af53fa7bc58403bb80056ef
