### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by olibclarke** [tbepler/topaz#3]
Hi, I tried to build using docker, but got the attached error - thoughts?

Picker looks awesome, would love to give it a try!

Cheers
Oli

<img width="2141" alt="image" src="https://user-images.githubusercontent.com/19766818/46760053-eb564a00-cc9e-11e8-82b1-f264051802be.png">

**Comment by markbasham** [comment]
Think you need a sudo before your docker command, but I might be wrong.

**Comment by olibclarke** [comment]
Derp - yes of course you do! Sorry, brain malfunction :) Installing now
