### ISSUE TITLE
Error when importing load_image

### ISSUE THREAD

**Issue by Kajoura** [tbepler/topaz#32]
Hi Tristan,

I have installed Topaz and can't wait to give it a try to analyze my data!

I'm working through the "complete walkthrough". I have an issue when I do:
from topaz.utils.data.loader import load_image

ImportError                               Traceback (most recent call last)
<ipython-input-13-910e09cee400> in <module>()
----> 1 from topaz.utils.data.loader import load_image
ImportError: No module named topaz.utils.data.loader
NameError: name 'load_image' is not defined

Following steps work fine till I try to load the micrographs for visualization, since I need to use load_image.

Can you please help me to understand what is missing?

Thanks!

**Comment by tbepler** [comment]
It sounds like you don't have topaz installed in the same conda (or pip) environment as your jupyter kernel. If you are using conda, install jupyter into your topaz environment and then select that environment for your jupyter kernel. This is as simple as:

```
source activate topaz # or whatever you named your conda environment
conda install jupyter
#now launch jupyter and you can access the topaz environment
jupyter notebook
```

This stackoverflow thread may have more info: https://stackoverflow.com/a/39623487.

Hope that helps!

**Comment by Kajoura** [comment]
It does help! Thank you very much!

**Comment by tbepler** [comment]
Since it sounds like this is fixed, I'm going to close this issue. Feel free to reopen if the problem continues.
