### ISSUE TITLE
Request to add CUDA warning

### ISSUE THREAD

**Issue by nysbc** [tbepler/topaz#33]
We have Topaz installed on our cluster with Singularity and we ran into an issue that we solved, but it took some time and could have been solved much quicker with a simple warning in Topaz. Our scenario is that we have nodes with different versions of CUDA: some with 8, some with 9, and some with 10. Topaz runs on GPU fine on the nodes with 9 or 10, but when we run it on a node with 8, it silently falls back to CPU. Well, not completely silently. All you see is this:

using device=0 with cuda=False

When it is working, this says:

using device=0 with cuda=True

Could you add a warning for the user so that when device >= 0, but cuda=False, then Topaz tells you that it is falling back to CPU because the CUDA version is likely not 9+?

Thanks!

**Comment by tbepler** [comment]
Warning added in commit 70f54b20cfbdf7f35c0c519eeb8c6f8b42f5a507
