### ISSUE TITLE
THCudaCheck FAIL error

### ISSUE THREAD

**Issue by olibclarke** [tbepler/topaz#36]
Hi,

I'm trying to run Topaz on a test dataset (50 mic subset of EMPIAR-10288), but I am getting an error at the training step (see attached). This is using an RTX-2080, with CUDA 10.1 on Ubuntu 18.04. Topaz was installed using anaconda. It still seems to be running, so I'm wondering whether I can ignore this error, or if not are there any known solutions?

Cheers
Oli

![image](https://user-images.githubusercontent.com/19766818/64281252-bc813c00-cf20-11e9-883d-cf48c760a16d.png)

**Comment by tbepler** [comment]
In the past, I can only recall seeing this error when the GPU is out of RAM, but that should crash the program. Is the model still training correctly?

**Comment by olibclarke** [comment]
It seems to be - or at least model_training.txt is still being updated (screenshot below). Definitely not out of GPU ram - it is only using ~2GB. Probably nothing to worry about then.

Cheers
Oli

![image](https://user-images.githubusercontent.com/19766818/64284161-f05f6000-cf26-11e9-931a-34f188cb8314.png)

**Comment by tbepler** [comment]
It sounds fine then. If you run into this error again, I'd be interested to know. It's very strange...

**Comment by tbepler** [comment]
Ok, it looks like this is a known problem with RTX GPUs. There's a thread on it here (https://discuss.pytorch.org/t/a-error-when-using-gpu/32761/19). Apparently setting
```
torch.backends.cudnn.benchmark = True
```
when topaz launches will fix the problem (https://discuss.pytorch.org/t/a-error-when-using-gpu/32761/20).

**Comment by olibclarke** [comment]
Ok thanks! It seems harmless so far but if I run into any issues with the outputs I'll try that then.

Cheers
Oli

**Comment by olibclarke** [comment]
On another note - are there any benchmarks for training speed available? 

On my system it looks like it'll take ~1hr to train on 50 micrographs (K2 data, downsampled 8x), with 852 particles in the training set and N=500, running on an RTX-2080. Is this in line with expectations, more or less?

**Comment by tbepler** [comment]
I haven't rigorously benchmarked the speed, but that's roughly in line with what I've seen. The training time actually isn't dependent on the number of micrographs or particles, only the specified number of training iterations. By default, this is 5k iterations per epoch and 10 epochs, so 50k iterations. Also, the bottleneck in speed is often the data augmentation (random rotation of the training images), which can be sped up by increasing the number of threads (the --num-workers argument). If you haven't set this, you will probably see a dramatic improvement in training time by setting it to 8+ (depending on how many CPUs you have).

If you want to try something experimental, the 'dev' branch of topaz now includes pretrained models that can be used to initialize the model for training. I've found this can dramatically reduce the amount of training required (10x or more). If you try this, you can set --epoch-size=500 to see the difference.

**Comment by tbepler** [comment]
I'm going to close this issue since it seems to be resolved. Feel free to open a new issue if you have follow up questions.
