### ISSUE TITLE
Add warning for when micrograph image names include the file extension

### ISSUE THREAD

**Issue by tbepler** [tbepler/topaz#44]
Including the file extension in the micrograph name causes topaz to fail to find micrographs. See for example https://github.com/tbepler/topaz/blob/master/topaz/commands/train_test_split.py#L30

It would be great if topaz could correct these names automatically, but a warning when micrograph names contain "." is a good place to start.

**Comment by DarnellGranberry** [comment]
https://github.com/tbepler/topaz/commit/b1f163b16e14d9a9ea4e243d8d34e3daeff21d55 includes automatically removing common file extensions from images
