### ISSUE TITLE
Topaz commands not running.

### ISSUE THREAD

**Issue by ACheong97** [tbepler/topaz#45]
I installed the topaz environment with Python 3.6. When I try to enter a command, I get the following:
>>topaz --help
'topaz' is not recognized as an internal or external command,
operable program or batch file.
I checked my paths and I am sure I am running on 3.6 so I am not sure what is going on.
Any help would be nice!

**Comment by tbepler** [comment]
Did you install topaz following the anaconda instructions [here](https://github.com/tbepler/topaz#install-topaz)? If so, you probably need to activate your conda environment before running topaz:
```
source activate topaz
topaz --help
```

**Comment by ACheong97** [comment]
Yes, I activated my environment but with "conda activate topaz" since my Anaconda version is later than 4.4, but it still does not work.

**Comment by tbepler** [comment]
What is the output of 'conda list' inside your topaz environment?

**Comment by ACheong97** [comment]
![image](https://user-images.githubusercontent.com/32020345/73232725-0cafa380-4139-11ea-8199-c64ba42f31ce.png)
Looks something like this.

**Comment by tbepler** [comment]
It looks like topaz is not installed in your environment. Try running the topaz install commands again with the environment activated.

**Comment by ACheong97** [comment]
I installed topaz and when I use conda list, I can see topaz is now installed in the environment. I ran topaz --help and got: Program 'topaz' failed to run: No application is associated with the specified file for this operation

**Comment by tbepler** [comment]
I suspect this is an issue with conda on windows, but unfortunately I don't have a windows machine on hand to investigate. Apparently conda may not play nicely with powershell (https://stackoverflow.com/a/54811138). Do other programs work from within the environment? E.g. will jupyter notebook launch?

**Comment by ACheong97** [comment]
Notebook works fine. The same issue persists after adding the path to the topaz environment and after installing PSCondaEnvs from the 1st link.

**Comment by tbepler** [comment]
Have you tried installing topaz from source?

**Comment by ACheong97** [comment]
I was able to successfully run topaz denoise --help after executing "pip install ." I am pretty sure it works now. Thanks for the help.

**Comment by tbepler** [comment]
Great, sorry the conda install was such a problem. I'll need to find a windows computer to look into this further.

**Comment by TimYi** [comment]
I find another approach to get it work on windows:

1. find topaz executable file: C:\Users\$USER\Anaconda3\envs\topaz\Scripts\topaz.py
2. rename it to topaz.bat
3. change it's content to: `python -m topaz.main %*`
