### ISSUE TITLE
Is there a way to decrease the restriction distance between predicted particles?

### ISSUE THREAD

**Issue by Zivvvo** [tbepler/topaz#62]
Greetings, I am a researcher working on Cryo-EM 3D reconstruction of microtubule proteins, specifically the doublet microtubules from cilia and flagella. We are currently using topaz to perform automatic picking of filamentous structures. Currently, topaz is picking very well except that there seems to be a fixed minimum distance between neighboring particles. How to achieve a denser extraction and which of the parameters should be changed during the extraction?

Extraction command:
topaz extract -r 40 -m saved_models_full_pick/model_epoch10.sav \
              -o data/topaz_full_pick/predicted_particles_all.txt \
              data/processed/training_micrographs/*.mrc

Picking results:
![image](https://user-images.githubusercontent.com/54366100/89683301-862d0900-d8b5-11ea-84cd-c42ddc3e0b0b.png)

Ground truth:
![image](https://user-images.githubusercontent.com/54366100/89683252-6eee1b80-d8b5-11ea-8134-dc8a46cfa6e8.png)

**Comment by tbepler** [comment]
I'm glad you're getting good results! Increasing the extracted particle density is as easy as reducing the radius parameter for `topaz extract`. This parameter sets the minimum distance (in pixels) allowed between particle centers. For example, if you wanted to allow 5 pixels between centers, you would replace `-r40` with `-r5` in your command.

**Comment by tbepler** [comment]
Closing this issue since the questions seems to be resolved!
