### ISSUE TITLE
3D demonising and ctf correction

### ISSUE THREAD

**Issue by samuelhaysom** [tbepler/topaz#71]
I'm not sure if this is the best forum for this question but I was wondering if the included general models for 3D demonising of tomograms was trained on tomograms that are ctf corrected? If so, will it matter if I use it to Denoise non-CTF corrected micrographs or, if that is my intended use, should I train a new model for this purpose?

**Comment by tbepler** [comment]
The tomograms used for training were not CTF corrected, but I don't expect there will be a noticeable difference in performance if denoising CTF corrected ones.

**Comment by tbepler** [comment]
I'm going to close this issue since it seems like there aren't any other questions.
