### ISSUE TITLE
Minor documentation 

### ISSUE THREAD

**Issue by bHimes** [tbepler/topaz#8]
Matplotlib is mentioned as necessary for visualization in the tutorial, but not as a core dependency. 

Just running

>$ topaz --help 

requires matplotlib to be installed.

Not so significant, but I think matplotlib should be listed in the deps for installing from source.

**Comment by tbepler** [comment]
That should not be the case. Which version of topaz do you have install? If you installed from source, can you tell me which commit?

**Comment by bHimes** [comment]
The version is 0.1.0, commit 70f5f04

Interestingly, after setting up a new conda environment just for topaz to solve the pytorch version problem in [issue #9](https://github.com/tbepler/topaz/issues/9) and without installing matplotlib, I did not run into the same problem.

I tried uninstalling matplotlib in my base, but the problem was not reproducible. 

Sorry for the confusion!

**Comment by tbepler** [comment]
Great, glad to hear that resolved everything.
