### ISSUE TITLE
topaz 0.2.5 not available through shub, conda, or pip.

### ISSUE THREAD

**Issue by ulloaa** [tbepler/topaz#86]
Are you guys planning on making topaz 0.2.5 available on shub, conda or pip? Thanks.

**Comment by tbepler** [comment]
Yes, we will be releasing 0.2.5 on conda, pip, etc. https://github.com/tbepler/topaz/issues/81

**Comment by dzyla** [comment]
Hi,

It is still not available to download via pip or conda. Could you tell how to get it?

**Comment by tbepler** [comment]
You can install using the "from source" instructions (https://github.com/tbepler/topaz#install-the-dependencies).

**Comment by dzyla** [comment]
I tried to do it from the source but it is not possible to checkout version 0.2.5:

git checkout v0.
v0.0.0   v0.1.0   v0.2.0   v0.2.1   v0.2.2   v0.2.3   v0.2.4   

Any ideas?

**Comment by tbepler** [comment]
0.2.5 isn't tagged yet, but you can use the current development version by installing from the master branch which is 0.2.5.

**Comment by rajssai** [comment]
Is there way to update topaz from 2.4 to 2.5 in conda environment using CLI

**Comment by Anthchirp** [comment]
There is still no 0.2.5 uploaded to conda, https://anaconda.org/tbepler/topaz/files

**Comment by DarnellGranberry** [comment]
Hi all, version 0.2.5a has been deployed to [PyPI](https://pypi.org/project/topaz-em/0.2.5a0/) and [Anaconda](https://anaconda.org/tbepler/topaz).

**Comment by Anthchirp** [comment]
Is the prerelease marking intentional or is this considered a stable release?

**Comment by DarnellGranberry** [comment]
> Is the prerelease marking intentional or is this considered a stable release?

Hi @Anthchirp, thanks for pointing that out. I've corrected the version number, so it is no longer shown as a prerelease.
