### ISSUE TITLE
Support for Cuda 11

### ISSUE THREAD

**Issue by alexjnoble** [tbepler/topaz#98]
Oli reports here that Cuda 11.2 seems to not be compatible with Topaz:

https://discuss.cryosparc.com/t/topaz-train-error-in-csparc-3-2/6500

Can support be added?

Thanks,
-Alex

**Comment by tbepler** [comment]
Looks like the cryoSPARC team got topaz to run with CUDA 11.1, so I don't think this is a topaz issue. Looks like it was just an installation problem with pytorch.
